local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>f', function()
  require('telescope.builtin').find_files({ cwd = vim.g.start_dir })
end, { desc = 'Telescope find files (directorio de inicio)' })
vim.keymap.set('n', '<C-f>', builtin.git_files, { desc = 'Telescope find files in git' })
local builtin = require('telescope.builtin')
